config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :projects
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end

  devise_for :users
  root to: 'projects#index' # changed from 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_rich_text :description
  has_one_attached :thumbnail
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :projects, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_paramters, if: :devise_controller?
  
  protected

  def configure_permitted_paramters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password)}
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  
  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)
    @project.user_id = current_user.id
    

    
      if @project.save
        redirect_to action: 'index'
      else
        respond_to do |format|
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    if @project.update(project_params)
        redirect_to @project
      else
        respond_to do |format|
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :donation_goal, :description, :thumbnail)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def author_of(resource)
    user_signed_in? && current_user.id == resource.user_id
  end

  def admin?
    user_signed_in? && current_user.admin?
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BackMy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body >
    <%= yield %>
  </body class = "p-0 m-0">
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true, multipart: true) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :donation_goal, style: "display: block" %>
    <%= form.text_field :donation_goal %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.rich_text_area :description %>
  </div>
  <div>
    <%= form.label :thumbnail,  "Project thumbnail", style: "display: block" %>
    <%= form.file_field :thumbnail %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Title:</strong>
    <%= project.title %>
  </p>

  <p>
    <strong>Donation goal:</strong>
    <%= project.donation_goal %>
  </p>
  <p>
    <strong>Description:</strong>
    <%= truncate(strip_tags(project.description)) %>
  </p>

  <p>
    <strong>User:</strong>
    <%= project.user.email %>
  </p>

</div>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render "form", project: @project %>

app/views/projects/index.html.erb
<h1 class = "d-flex justify-content-center align-items-center bg-dark text-light m-0 p-0 w-100">Projects</h1>

<p style="color: green"><%= notice %></p>

<div class = "d-flex flex-col flex-wrap w-100 ">
  <% @projects.each do |project| %>
  
  <div class = "w-25 fs-4 mt-4 border thirty" ><h4 class= "text-center" >Title:  <%=project.title %> </h4>
  <p class= "text-center"> Donation goal: <%= project.donation_goal%> </p>
  <div class= "text-center">  Description:
  <%= truncate(strip_tags(project.description.to_s),length: 140)%>
 </div>
 <div class = "d-flex justify-content-center align-items-center">
  
  <%= image_tag project.thumbnail, class: "w-25 h-25 " if project.thumbnail.present?  %>
  </div> 
 
   <div class= "text-center "><%= link_to('Edit this project', edit_project_path(project),class:'bg-sky-600 m-3 p-1 rounded') %></div>
   </div>


    

  <% end %>
</div>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @project %>

<div>
  <%= link_to "Edit this project", edit_project_path(@project) %> |
  <%= link_to "Back to projects", projects_path %>

  <%= button_to "Destroy this project", @project, method: :delete %>
</div>